# Generated by Django 3.1.1 on 2020-09-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
